# The URL the site will be built for
base_url = "https://jahongir.ru"
# base_url = "xpltt.vercel.app"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = false
generate_robots_txt = true
generate_feeds = true
feed_filenames = ["rss.xml"]
title = "Jahongir Ahmadaliev"
description = "Личный блог про технологии"
default_language = "ru"
theme = "sam"
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
taxonomies = [
{ name = "tags", rss = true },
{ name = "authors", rss = true }
]

[markdown]
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[markdown.highlighting]
enabled = true
theme = "nord"

[extra]
date_format = "%d.%m.%Y"  #  08.03.2025
comments = true
home = "Главная"
sam_menu = [
    { text = "Заметки", link = "/blog" },
    { text = "Обо мне", link = "/about" },
    { text = "GitHub", link = "https://github.com/jahamars" },
    { text = "Ачивки", link = "/sert" }
]
sam_bottom_menu = true
show_word_count = true
show_reading_time = true
