base_url = "https://jahongir.ru"


compile_sass = true
minify_html = true  
generate_robots_txt = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]  

title = "DevSecOps notes"
description = "блог про технологии и не только"
default_language = "ru"
theme = "prism"

build_search_index = false

# Taxonomies
taxonomies = [
    { name = "tags", feed = true },
    { name = "authors", feed = true },
    { name = "categories", feed = true }
]

[markdown]
render_emoji = true
external_links_target_blank = true
# external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

highlighting = { theme = "material-theme-darker" }

[extra]
keywords = "DevOps, Linux, Cloud, Docker, Kubernetes, CI/CD, Ansible, Terraform, Jahongir Ahmadaliev, Жахонгир Ахмадалиев"
author = "Jahongir Ahmadaliev"
banner = "favicon/android-chrome-512x512.png"
show_toc = true


# background_gradient = "#282828"
#background_image = "https://raw.githubusercontent.com/Jahamars/blog/refs/heads/main/static/photos/1.jpeg"
background_image = "https://raw.githubusercontent.com/Jahamars/blog/refs/heads/main/static/photos/3.jpg"

date_format = "%d.%m.%Y"

comments = true
home = "Back"
show_word_count = true
show_reading_time = true

sam_menu = [
    { text = "Заметки", link = "/blog" },
    { text = "Авторы", link = "/authors" },
    { text = "Обо мне", link = "/about" },
    { text = "GitHub", link = "https://github.com/jahamars" },
    { text = "Ачивки", link = "/sert" },
    { text = "TECH talks", link = "/talks" }
    # { text = "Категории", link = "/categories" },
    # { text = "Теги", link = "/tags" },
    # { text = "RSS", link = "/rss.xml" }
]

sam_bottom_menu = true

[extra.giscus]
enabled = true
repo = "jahamars/blog"
repo_id = "R_kgDOOGPcjw"
category = "Announcements"
category_id = "DIC_kwDOOGPcj84C0ShM"
mapping = "pathname"
strict = "0"
reactions_enabled = "1"
emit_metadata = "0"
input_position = "bottom"
theme = "transparent_light"
lang = "ru"

# Google Analytics
[extra.analytics]
google_analytics_id = "G-ELR5QJ5CKK"

# Footer
# [extra.sam_footer]
# text = "Built using Zola & Prism theme"

# Author (optional)
# [extra.author]
# name = "Jahongir Ahmadaliev"
# email = ""
# url = "https://jahongir.ru"

# Features
[extra.features]
copy_code_button = true
reading_progress_bar = true
smooth_scroll = true
