[build]
  command = "zola build"
  publish = "public"

[build.environment]
  ZOLA_VERSION = "0.20.0" 

# [[redirects]]
  # from = "/about/*"
  # to = "https://jahamars.github.io/:splat"
  # status = 200
  # force = true

[[redirects]]
  from = "/sert/*"
  to = "https://jahamars.github.io/sert/:splat"
  status = 200
  force = true
